In [1]:
import fastf1
import pandas as pd
import numpy as np

In [4]:
import os

os.makedirs("../data/fastf1_cache", exist_ok=True)

fastf1.Cache.enable_cache("../data/fastf1_cache")

print("FastF1 cache enabled successfully!")

FastF1 cache enabled successfully!

In [5]:
session = fastf1.get_session(2025,"British","R")
session.load()

core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 43)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 30: Position data is incomplete!
_api        WARNING 	Driver 31: Position data is incomplete!
_api        WARNING 	Driver  2: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
_api        WARNING 	Driver  7: Position data is incomplete!
_api        WARNING 	Driver  8: Position data is incomplete!
_api        WARNING 	Driver  9: Position data is incomplete!
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 15: Position data is incomplete!
_api        WARNING 	Driver 17: Position data is incomplete!
_api        WARNING 	Driver 19: Position data is incomplete!
_api        WARNING 	Driver 20: Position data is incomplete!
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 25: Position data is incomplete!
_api        WARNING 	Driver 26: Position data is incomplete!
_api        WARNING 	Driver 28: Position data is incomplete!
_api        WARNING 	Driver 29: Position data is incomplete!
_api        WARNING 	Driver 43: Position data is incomplete!
_api        WARNING 	Driver 44: Position data is incomplete!
_api        WARNING 	Driver 55: Position data is incomplete!
_api        WARNING 	Driver 63: Position data is incomplete!
_api        WARNING 	Driver 81: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

In [7]:
results = session.results
results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,1.0,1,3.0,NaT,NaT,NaT,0 days 01:37:15.735000,Finished,25.0,52.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:06.812000,Finished,18.0,52.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,01C00E,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,3.0,3,19.0,NaT,NaT,NaT,0 days 00:00:34.742000,Finished,15.0,52.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:39.812000,Finished,12.0,52.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,5.0,5,1.0,NaT,NaT,NaT,0 days 00:00:56.781000,Finished,10.0,52.0

In [9]:
results.to_csv("../data/raw/race_results/british_gp_2025.csv",index=False)

In [12]:
qualifying = fastf1.get_session(2025, "British", "Q")
qualifying.load()

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver  1: Position data is incomplete!
_api        WARNING 	Driver  4: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver 10: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 14: Position data is incomplete!
_api        WARNING 	Driver 16: Position data is incomplete!
_api        WARNING 	Driver 18: Position data is incomplete!
_api        WARNING 	Driver 22: Position data is incomplete!
_api        WARNING 	Driver 23: Position data is incomplete!
_api        WARNING 	Driver 27: Position data is incomplete!
_api        WARNING 	Driver 43: Position data is incomplete!
_api        WARNING 	Driver 44: Position data is incomplete!
_api        WARNING 	Driver 55: Position data is incomplete!
_api        WARNING 	Driver 63: Position data is incomplete!
_api        WARNING 	Driver 81: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '44', '16', '12', '87', '14', '10', '55', '22', '6', '23', '31', '30', '5', '18', '27', '43']

In [13]:
q_results = qualifying.results
q_results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,1.0,,NaN,0 days 00:01:25.886000,0 days 00:01:25.316000,0 days 00:01:24.892000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,2.0,,NaN,0 days 00:01:25.963000,0 days 00:01:25.316000,0 days 00:01:24.995000,NaT,,NaN,NaN
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,3.0,,NaN,0 days 00:01:26.123000,0 days 00:01:25.231000,0 days 00:01:25.010000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,4.0,,NaN,0 days 00:01:26.236000,0 days 00:01:25.637000,0 days 00:01:25.029000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,,NaN,0 days 00:01:26.296000,0 days 00:01:25.084000,0 days 00:01:25.095000,NaT,,NaN,NaN

In [15]:
import os

print(os.getcwd())

C:\Users\chris\Desktop\APEX\notebooks

In [16]:
q_results.to_csv(
    "../data/raw/qualifying/british_gp_2025.csv",
    index=False
)

print("Successful!")

Successful!

In [18]:
laps = session.laps
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:55.042000,VER,1,0 days 00:01:45.820000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.707000,...,True,Red Bull Racing,0 days 00:56:09.003000,2025-07-06 14:03:49.616,12,1.0,False,,False,False
1,0 days 01:00:10.640000,VER,1,0 days 00:02:15.598000,2.0,1.0,NaT,NaT,0 days 00:00:45.755000,0 days 00:00:53.700000,...,True,Red Bull Racing,0 days 00:57:55.042000,2025-07-06 14:05:35.655,26,1.0,False,,False,False
2,0 days 01:02:27.997000,VER,1,0 days 00:02:17.357000,3.0,1.0,NaT,NaT,0 days 00:00:48.885000,0 days 00:00:50.924000,...,True,Red Bull Racing,0 days 01:00:10.640000,2025-07-06 14:07:51.253,6,1.0,False,,False,False
3,0 days 01:04:13.565000,VER,1,0 days 00:01:45.568000,4.0,1.0,NaT,NaT,0 days 00:00:36.223000,0 days 00:00:40.712000,...,True,Red Bull Racing,0 days 01:02:27.997000,2025-07-06 14:10:08.610,6712,1.0,False,,False,False
4,0 days 01:05:58.374000,VER,1,0 days 00:01:44.809000,5.0,1.0,NaT,NaT,0 days 00:00:31.996000,0 days 00:00:43.110000,...,True,Red Bull Racing,0 days 01:04:13.565000,2025-07-06 14:11:54.178,126,1.0,False,,False,False

In [19]:
laps.to_csv("../data/raw/laps/british_gp_2025.csv",index=False)
print("succesful")

succesful

In [20]:
laps.columns.tolist()

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']

In [26]:
stint_col = ["Driver","LapNumber","LapTime","Compound","TyreLife","Stint"]
stints = laps[stint_col].copy()

In [27]:
stints.head()

  Driver  LapNumber                LapTime      Compound  TyreLife  Stint
0    VER        1.0 0 days 00:01:45.820000  INTERMEDIATE       1.0    1.0
1    VER        2.0 0 days 00:02:15.598000  INTERMEDIATE       2.0    1.0
2    VER        3.0 0 days 00:02:17.357000  INTERMEDIATE       3.0    1.0
3    VER        4.0 0 days 00:01:45.568000  INTERMEDIATE       4.0    1.0
4    VER        5.0 0 days 00:01:44.809000  INTERMEDIATE       5.0    1.0

In [41]:
stints.to_csv("../data/raw/stints/british_gp_2025.csv",index=False)
print("succesful")

succesful

In [31]:
print(laps.columns.tolist())

['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

In [32]:
pit_stops = laps[laps["PitInTime"].notna()][["Driver", "LapNumber", "PitInTime", "PitOutTime"]].copy()

In [33]:
pit_stops.head()

    Driver  LapNumber              PitInTime PitOutTime
10     VER       11.0 0 days 01:17:23.948000        NaT
40     VER       41.0 0 days 02:16:41.355000        NaT
62     GAS       11.0 0 days 01:17:34.025000        NaT
92     GAS       41.0 0 days 02:16:43.664000        NaT
105    ANT        2.0 0 days 01:00:08.067000        NaT

In [34]:
pit_stops.to_csv("../data/raw/pit_stops/british_gp_2025.csv",index=False)
print("Succesful")

Succesful

In [35]:
weather = session.weather_data

In [36]:
weather.head

<bound method NDFrame.head of                       Time  AirTemp  Humidity  Pressure  Rainfall  TrackTemp  \
0   0 days 00:00:19.723000     18.0      85.0     988.6     False       24.2
1   0 days 00:01:19.675000     18.0      83.0     988.5     False       24.6
2   0 days 00:02:19.683000     18.1      82.0     988.6     False       24.6
3   0 days 00:03:19.685000     18.0      81.0     988.6     False       24.1
4   0 days 00:04:19.683000     18.0      79.0     988.5     False       23.9
..                     ...      ...       ...       ...       ...        ...
150 0 days 02:30:20.275000     19.3      65.0     989.1     False       24.4
151 0 days 02:31:20.287000     19.4      64.0     989.0     False       24.4
152 0 days 02:32:20.278000     19.5      65.0     989.0     False       24.6
153 0 days 02:33:20.278000     19.5      64.0     989.0     False       24.6
154 0 days 02:34:20.295000     19.6      63.0     988.9     False       24.3

     WindDirection  WindSpeed
0              174        0.7
1              111        0.9
2               61        2.2
3               71        3.1
4               28        3.0
..             ...        ...
150             95        1.1
151            230        1.9
152            287        1.5
153             48        1.6
154             99        1.7

[155 rows x 8 columns]>

In [37]:
weather.columns

Index(['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp',
       'WindDirection', 'WindSpeed'],
      dtype='object')

In [38]:
weather.to_csv("../data/raw/weather/british_gp_2025.csv", index=False)
print("succesful")

succesful

In [40]:
print("RACE RESULTS:", results.shape)
print("QUALIFYING:", q_results.shape)
print("LAPS:", laps.shape)
print("STINTS:", stints.shape)
print("PIT STOPS:", pit_stops.shape)
print("WEATHER:", weather.shape)

RACE RESULTS: (20, 22)
QUALIFYING: (20, 22)
LAPS: (825, 31)
STINTS: (825, 6)
PIT STOPS: (36, 4)
WEATHER: (155, 8)